### ISSUE TITLE
Procedure to install dependancies

### ISSUE THREAD

**Issue by GeorgeGkas** [cyberpython/lingua#10]
Please update the `Readme.md` file with commands to install the dependencies for other linuxes.
Moreover `sudo apt-get install lingua` exit with `E: Unable to locate package lingua` error message.
Thanks.

**Comment by cyberpython** [comment]
The number of different Linux distributions and package managers makes it hard to maintain detailed instructions for all the possible combinations, thus a list of the required libraries and applications is provided in the README file.

The error you are getting is because the PPA does not have a build available for Ubuntu 15.04.
But you can install the application on Ubuntu 15.04 by following the instructions in README.md (the only deviation being that the latest release of the glossa-interpreter - 1.0.8 - needs to be installed first. I will update the README file as soon as possible):

__Make sure the Ubuntu 'universe' repository is enabled in the 'Ubuntu Software Sources' application.__


__Install the dependencies with:__

    sudo apt-get install openjdk-7-jdk antlr3 libjoptsimple-java libjava-gnome-j* 


__Install the latest glossa-interpreter:__

    cd ~
    wget https://dl.dropboxusercontent.com/u/599926/releases/glossa-interpreter-1.0.8.tar.gz
    tar -xvf glossa-interpreter-1.0.8.tar.gz
    cd glossa-interpreter-1.0.8
    make
    sudo make install

__Install the latest lingua version:__

    cd ~
    wget https://dl.dropboxusercontent.com/u/599926/releases/lingua-0.0.6.tar.gz
    tar -xvf lingua-0.0.6.tar.gz
    cd lingua-0.0.6
    make
    sudo make install

__Run lingua:__

    lingua
